project:
  type: website
  output-dir: docs

website:
  title: "Internal Validation Methods Comparison"
  navbar:
    left:
      - text: "Paper"
        href: paper.html
      - text: "Code"
        href: simulation_code.R
      - text: "Results"
        href: validation_results.csv

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: false
    self-contained: false
