project:
  type: website
  output-dir: docs

website:
  title: "Internal Validation Methods Comparison"
  navbar:
    left:
      - text: "Internal Validation"
        href: index.qmd
      - text: "Sample splitting"
        href: sample_splitting.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: false
    self-contained: false
